=== 24f3003330/Web-Application-Development/bookstore.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, genre, author, price, publish_date, isbn)>
<!ATTLIST book id ID #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT author (name, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency (USD|EUR|GBP|INR) "USD">
<!ELEMENT publish_date (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>

=== 24f3003330/Web-Application-Development/bookstore_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<bookstore>
    <book id="B101">
        <title>XML &amp; Web Services</title>
        <genre>Computer</genre>
        <author>
            <name>John Doe</name>
            <email>jdoe@example.com</email>
        </author>
        <price currency="USD">49.95</price>
        <publish_date>2025-01-15</publish_date>
        <isbn>978-1-23456-789-7</isbn>
    </book>
    <book id="B102">
        <title>Advanced XML Techniques</title>
        <genre>Software Engineering</genre>
        <author>
            <name>Jane Smith</name>
            <email>jsmith@books.org</email>
        </author>
        <price currency="EUR">59.50</price>
        <publish_date>2024-11-22</publish_date>
        <isbn>978-9-87654-321-0</isbn>
    </book>
    <book id="B103">
        <title>Data Structures in Depth</title>
        <genre>Computer Science</genre>
        <author>
            <name>Robert C. Martin</name>
            <email>unclebob@cs.org</email>
        </author>
        <price currency="USD">39.99</price>
        <publish_date>2023-05-10</publish_date>
        <isbn>978-0-98765-432-1</isbn>
    </book>
    <book id="B104">
        <title>Clean Code Principles</title>
        <genre>Programming</genre>
        <author>
            <name>Martin Fowler</name>
            <email>mfowler@clean.org</email>
        </author>
        <price currency="GBP">45.00</price>
        <publish_date>2022-08-30</publish_date>
        <isbn>978-1-99887-654-3</isbn>
    </book>
</bookstore>

=== 24f3003330/Web-Application-Development/bookstore_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">

    <book id="B101">
        <title>XML &amp; Web Services</title>
        <genre>Computer</genre>
        <author>
            <name>John Doe</name>
            <email>jdoe@example.com</email>
        </author>
        <price currency="USD">49.95</price>
        <publish_date>2025-01-15</publish_date>
        <isbn>978-1-23456-789-7</isbn>
    </book>

    <book id="B102">
        <title>Advanced XML Techniques</title>
        <genre>Software Engineering</genre>
        <author>
            <name>Jane Smith</name>
            <email>jsmith@books.org</email>
        </author>
        <price currency="EUR">59.50</price>
        <publish_date>2024-11-22</publish_date>
        <isbn>978-9-87654-321-0</isbn>
    </book>

    <book id="B103">
        <title>Data Structures in Depth</title>
        <genre>Computer Science</genre>
        <author>
            <name>Robert C. Martin</name>
            <email>unclebob@cs.org</email>
        </author>
        <price currency="USD">39.99</price>
        <publish_date>2023-05-10</publish_date>
        <isbn>978-0-98765-432-1</isbn>
    </book>

    <book id="B104">
        <title>Clean Code Principles</title>
        <genre>Programming</genre>
        <author>
            <name>Martin Fowler</name>
            <email>mfowler@clean.org</email>
        </author>
        <price currency="GBP">45.00</price>
        <publish_date>2022-08-30</publish_date>
        <isbn>978-1-99887-654-3</isbn>
    </book>

    <book id="B105">
        <title>Introduction to Algorithms</title>
        <genre>Algorithms</genre>
        <author>
            <name>Thomas H. Cormen</name>
            <email>tcormen@algo.edu</email>
        </author>
        <price currency="USD">89.95</price>
        <publish_date>2021-12-01</publish_date>
        <isbn>978-0-26203-384-8</isbn>
    </book>

    <book id="B106">
        <title>The Art of Computer Programming</title>
        <genre>Theory</genre>
        <author>
            <name>Donald E. Knuth</name>
            <email>knuth@taocp.org</email>
        </author>
        <price currency="INR">2500</price>
        <publish_date>2019-07-25</publish_date>
        <isbn>978-0-20163-011-0</isbn>
    </book>

</bookstore>
